services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres_capstone
    profiles: ["dev", "qa"]
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend_capstone
    profiles: ["qa"]
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: smart_service
      PORT: 3000
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-super-secret}
      RUN_SEED: ${RUN_SEED:-false}
    ports:
      - "3000:3000"

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio_capstone
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: minio123
  #   command: server /data --console-address ":9001"
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - minio_data:/data

  # redis:
  #   image: redis:8
  #   container_name: redis_capstone
  #   ports:
  #     - "6379:6379"
  #   restart: always

volumes:
  pgdata:
  # minio_data:
